clearfeed/quix

package.json
yarn.lock

- Removed `@clearfeed-ai/quix-postgres-agent` from `package.json`.
- This package was not installing correctly and is no longer required for the project.
While running `yarn install`, the package `@clearfeed-ai/quix-postgres-agent` failed to install due to [insert reason if known, e.g., "registry issues" or "dependency conflicts"]. After investigation, it was determined that this package is no longer needed in the project.
- No functionality is affected as the package was not in use.
- The `yarn.lock` file has been updated to reflect the removal.
- Ran `yarn install` successfully after removal.

chore: remove unused @clearfeed-ai/quix-postgres-agent dependency

---

.env.example

The `.env.example` file was missing the `SLACK_SIGNING_SECRET` environment variable, which is required for Slack request verification.

fix: add missing SLACK_SIGNING_SECRET to .env.example

---

agent-packages/packages/jira/package.json
agent-packages/packages/jira/src/JiraClient.ts
agent-packages/packages/jira/src/index.ts
agent-packages/packages/jira/src/tools.ts
agent-packages/packages/jira/src/types/index.ts
package.json
src/database/migrations/03-add-default-project-to-jira-sites.js
src/database/models/jira-site.model.ts
src/llm/tool.service.ts
yarn.lock

- Increment @clearfeed-ai/quix-jira-agent to version 1.2.5 in package.json and yarn.lock
- Modify ToolService to conditionally pass default configuration for Jira tools
- Improve Jira tool initialization by handling optional default configuration more explicitly

Support default project specification in JIRA

---

src/database/database.module.ts
src/database/migrations/05-create-hubspot-configs.js
src/database/models/hubspot-config.model.ts
src/database/models/index.ts
src/database/models/slack-workspace.model.ts
src/integrations/integrations-install.service.ts
src/integrations/integrations.controller.ts
src/integrations/types.ts
src/lib/constants.ts
src/slack/views/app_home.ts
src/slack/views/types.ts

- Introduce HubSpot configuration model and migration for storing HubSpot OAuth tokens and related information.
- Update database module to include HubSpotConfig model.
- Enhance IntegrationsInstallService to handle HubSpot OAuth flow and store access tokens.
- Modify IntegrationsController to include a new endpoint for HubSpot connection.
- Update constants to define HubSpot scopes and integrate them into the application.
- Adjust Slack workspace model to establish a relationship with HubSpotConfig.
- Enhance app home view to display HubSpot connection status.

feat: Add HubSpot integration support

---

agent-packages/packages/hubspot/package.json
agent-packages/packages/hubspot/src/index.ts
agent-packages/packages/hubspot/src/types.ts
package.json
src/database/migrations/05-create-hubspot-configs.js
src/database/models/hubspot-config.model.ts
src/integrations/integrations.service.ts
src/lib/constants.ts
src/llm/tool.service.ts
yarn.lock

- Bump version of `@clearfeed-ai/quix-hubspot-agent` to 1.1.2 in package.json and yarn.lock
- Change `apiKey` to `accessToken` in HubspotConfig interface and related implementations
- Enhance HubspotService to validate access token configuration
- Update database migration to ensure unique hub_id in hubspot_configs table
- Implement refresh token logic in IntegrationsService for HubSpot configuration management
- Add new HubSpot scopes for improved API access

chore(hubspot): Update HubSpot agent version to 1.1.2 and refactor configuration handling

---

agent-packages/packages/zendesk/package.json
agent-packages/packages/zendesk/src/tools.ts
agent-packages/packages/zendesk/src/types.ts

✅ What’s done:
- Added support for creating a Zendesk client using an OAuth token.

feat(integration): Add support for OAuth in Zendesk

---

src/database/models/slack-workspace.model.ts
src/lib/types/slack-workspace.ts
src/lib/utils/slack-constants.ts
src/slack/app_home.service.ts
src/slack/interactions.service.ts
src/slack/slack-events-handler.service.ts
src/slack/views/app_home.ts
src/slack/views/modals.ts

- Added methods for managing access controls in the SlackWorkspace model, allowing for bulk addition of channel IDs and setting user access levels.
- Updated AppHomeService to handle new access control interactions and submissions.
- Enhanced Slack event handling to check user and channel authorization.
- Introduced new modals and views for managing access controls in the Slack app home.
- Updated slack-constants with new action identifiers for access control management.

feat(slack): Implement access control management in Slack integration

---

src/lib/constants.ts
src/llm/mcp.service.ts
src/llm/tool.service.ts

- Introduced support for Slack integration by adding it to the SUPPORTED_INTEGRATIONS enum.
- Updated the MCP service to include a mapping for Slack's MCP server.
- Enhanced ToolService to retrieve tools for Slack integration, improving the overall functionality of the integration system.

[FEAT]: Add Slack integration support in MCP service

---

.cursorrules
src/database/migrations/20240401_create_linear_config.js
src/database/models/index.ts
src/database/models/linear-config.model.ts
src/database/models/slack-workspace.model.ts
src/integrations/integrations-install.service.ts
src/integrations/integrations.service.ts
src/lib/constants.ts
src/lib/utils/slack-constants.ts
src/llm/mcp.service.ts
src/llm/tool.service.ts
src/slack/app_home.service.ts
src/slack/interactions.service.ts
src/slack/views/app_home.ts
src/slack/views/modals.ts
src/slack/views/types.ts

- Introduced Linear integration with a new Sequelize model for `linear_configs` and corresponding database migration.
- Updated the `IntegrationsInstallService` to handle Linear API token validation and workspace details retrieval.
- Enhanced Slack app home and interactions to support Linear connection management.
- Updated constants and utility functions to accommodate Linear integration features.
- Ensured proper error handling and logging for Linear connection processes.

[FEAT]: Add Linear integration support

---

src/database/migrations/20240501_add_default_config_to_linear_configs.js
src/database/models/linear-config.model.ts
src/llm/mcp.service.ts
src/llm/tool.service.ts

Added option to specify defaults for linear configuration was added in the MCP tool.
Tested by calling the functions locally

feat: specify default teamId for linear

---

src/database/migrations/20240502_create_mcp_connections.js
src/database/models/index.ts
src/database/models/mcp-connection.model.ts
src/database/models/slack-workspace.model.ts
src/integrations/integrations-install.service.ts
src/integrations/integrations.service.ts
src/lib/utils/slack-constants.ts
src/slack/app_home.service.ts
src/slack/interactions.service.ts
src/slack/views/app_home.ts
src/slack/views/modals.ts
src/slack/views/types.ts

- Updated `AppHomeService` to support MCP connections in the connection overflow menu, allowing users to edit and disconnect MCP integrations.
- Modified `getIntegrationInfo` to include MCP connection details with appropriate block IDs for better interaction handling.
- Improved modals for MCP connections to provide clearer instructions regarding API token management and security.

Add support for external MCP server

---

agent-packages/packages/salesforce/package.json
agent-packages/packages/salesforce/src/index.ts
agent-packages/packages/salesforce/src/tools.ts
agent-packages/packages/salesforce/src/types/index.ts
yarn.lock

- Updated the Salesforce agent package version from 1.0.4 to 1.0.5.
- Modified `createTask` method to accept `whatId` instead of `opportunityId`.
- Enhanced task creation parameters to include an optional `type` attribute.
- Added new methods for describing Salesforce objects and searching accounts, improving integration functionality.

Add support to fetch salesforce accounts, create tasks against accounts

---

src/lib/utils/slack-constants.ts
src/slack/app_home.service.ts
src/slack/interactions.service.ts
src/slack/views/app_home.ts
src/slack/views/modals.ts
src/slack/views/types.ts

- Introduced GitHub configuration modal with fields for repository and owner.
- Updated app home service to handle GitHub configuration submissions.
- Enhanced interactions service to process GitHub configuration submissions.
- Modified Slack constants to include new GitHub action identifiers.
- Updated view types and modals to accommodate GitHub integration.
Screenshots for the flow:
1. Select Github and click on horizontal 3 dots
2. Enter default repo and owner, or make changes if already there
3. Click on Submit
4. It will update the DB.

feat(slack): Add GitHub default configuration support

---

agent-packages/packages/jira/package.json
agent-packages/packages/jira/src/index.ts
agent-packages/packages/jira/src/types/index.ts

Now the correct URLs are used to generate the response 
resolves #97 
Search Issues
Find Issue by id
Create issue
Add comment

fix(jira): return correct urls of issues and comments for searchIssues and addComment tools

---

agent-packages/packages/zendesk/package.json
package.json
yarn.lock

When the package version was bumped last time, latest changes weren't deployed. Probably happened because of some mistake during yarn build. Upgarded the version now and deployed it again. This time the correct set of changes got deployed.

chore: bump @clearfeed-ai/quix-zendesk-agent and its dependencies to version 1.1.3

---

src/llm/llm.service.ts

Result:
> [Nest] 11820  - 10/04/2025, 3:58:22 pm     LOG [LlmService] Selected tools: github. Reason: To retrieve details about a specific GitHub issue from the user's default repository.
> [Nest] 11820  - 10/04/2025, 4:00:09 pm     LOG [LlmService] Selected tools: hubspot. Reason: The user wants to retrieve HubSpot deals related to 'Enterprise', which requires accessing HubSpot CRM data.

feat(llm): Log reason for tool selection in response

---

agent-packages/packages/jira/package.json
agent-packages/packages/jira/src/JiraClient.ts

Fixed the JWT token generation. Earlier, we did not pass the params with the path, which resulted in an incorrect hash comparison, and the API threw an Unauthorized error.
Tested by querying for user and ticket info with the same query which earlier was throwing 401.

fix(JIRA): Fixed JWT token generation

---

agent-packages/packages/github/package.json
agent-packages/packages/github/src/index.ts
agent-packages/packages/github/src/tools.ts
agent-packages/packages/github/src/types.ts
agent-packages/packages/hubspot/package.json
package.json
yarn.lock

The API that we were using earlier to get the list of pull requests - [List PRs API](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests) have no way to filter PR by author. It fetches all the PRs(paginated) pointing to a base branch and then LLM filter's it by provided name. It is possible that only one PR of `achitJ` was coming in the response list.
I have changed this to - [Search Issues and PRs API](https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests) to fetch the Pull request with advanced filtering(including author, keyword etc)
**Key Changes:**
- Updated `listPullRequests` method to support filtering by author and keyword.
- Modified parameters to include `author`, `keyword`, and `order` for sorting.
- …

feat(github): Enhance pull request listing with additional filters.

---

src/slack/app_home.service.ts
src/slack/views/app_home.ts

Addresses Issue #171 
Added a “Join Slack Community” button to the App Home view so users can easily access our public Slack workspace. The new button appears as an accessory on a dedicated section in the onboarding flow.
Tested the functionality on the test workspace. The 'Join' button takes the user to the slack page to join the community.

feat(app_home): add Slack community link to home page

---

src/slack/views/app_home.ts

This PR implements a confirmation dialog before disconnecting any integration from the Quix Slack App Home to address issue #196 :
UI change:
1. Adds a Slack confirm object to every Overflow Menu that contains a “Disconnect” option (both standard integrations and MCP connections).
2. The dialog asks “Are you sure you want to disconnect {integrationName}?” and offers Yes, disconnect / Cancel.
I have tested the changes on my Slack test workspace by disconnecting a connected source. I've attached the screenshot of the confirmation dialog.

feat(app-home): add confirmation modal before disconnecting integrations

---

agent-packages/packages/jira/package.json
agent-packages/packages/jira/src/JiraClient.ts
agent-packages/packages/jira/src/index.ts
agent-packages/packages/jira/src/tools.ts
agent-packages/packages/jira/src/types/index.ts
package.json
yarn.lock

Closes issue #195 
This PR wires the new labels property end-to-end so any labels passed in from the Quix tool actually make it into the Jira API payload:
types.ts
• Added labels?: string[] to CreateIssueParams.
tools.ts
• Extended the Zod schema for the create_jira_issue tool to accept an optional labels array.
JiraService (index.ts)
• Included labels: params.labels when building the issueData object.
JiraClient (JiraClient.ts)
• Destructured labels from params and added labels into the fields payload for the POST /issue call.
The changes have been tested inside the slack test workspace. It was observed that the labels are getting created appropriately while filing a jira issue.

fix(jira): enforce labels and include them in issue creation payload

---

src/integrations/mcp.service.ts
src/lib/utils/encryption.ts
src/llm/llm.service.ts
src/slack/slack-events-handler.service.ts

When working locally, logs are required frequently for debugging purposes, which is whyI  made a change to only encrypt sensitive stuff on non-development environments
- Set NODE_ENV to production and tested that logs are getting encrypted
- Set NODE_ENV to production and tested that logs aren't getting encrypted

refactor(encryption): replace encrypt with encryptForLogs to not encrypt logs in local development

---

agent-packages/packages/github/package.json
agent-packages/packages/github/src/index.ts
agent-packages/packages/github/src/schema.ts
agent-packages/packages/github/src/tools.ts
agent-packages/packages/github/src/types.ts
package.json
yarn.lock

This change replaces the deprecated `issuesAndPullRequests` endpoint with the `.request()` method, which will automatically be overridden to use advanced search starting from September 4th. After this date, there will be no need to include the `advanced_search` parameter, as all issue queries will default to advanced search. Our code will remain unaffected by this transition.
- Renamed the handler from `searchIssues` to `searchIssuesOrPullRequests`, as it will now serve as the unified handler for searching both issues and pull requests.
- Removed the redundant `listIssues` and `listPullRequests` handlers, along with their associated tools and types.
- Added support for additional filters such as `label` and `assignee` to improve search precision.
- Limited `per_page` results to 5, as the …

chore(github): Remove deprecated `issuesAndPullRequests` method

---

src/llm/llm.service.ts

- Passing plan and custom instructions irrespective of number of tools selected.
- Perform a regression testing on jira and github tools and it is working as expected.
- Previously when only one tool was getting selected, there was a difference between plan and tool calling, now it is same.
For example: Previously when updating a jira issue.
- plan just contains to call `update_jira_issue`
- But, actually first `get_jira_issue` was called then `update_jira_issue`
**Now, only those tools are called which is mentioned in the plan.**

refactor(llm-service): Pass plan and custom instructions even when single tool is selected

---

.cursorrules
agent-packages/packages/jumpcloud/README.md
agent-packages/packages/jumpcloud/package.json
agent-packages/packages/jumpcloud/src/index.ts
agent-packages/packages/jumpcloud/src/integration.spec.ts
agent-packages/packages/jumpcloud/src/tools.ts
agent-packages/packages/jumpcloud/src/types.ts

added 2 functions - one to get devices assigned to a user by userid, and another to get all org devices. 
Used v1 api opposed to v2 as v2 requires an additional `ORG_ID` param to get systems in the org. 
Check screenshots and added tests to `integration.spec.ts`

+ jumpcloud device retrieval tools

---

agent-packages/packages/common/src/tools.ts
agent-packages/packages/common/src/types.ts
agent-packages/packages/github/src/tools.ts

Renamed the `operation` property to `operations` in `agent-packages/packages/common` and `agent-packages/packages/github` modules. This change was made to align with the requested naming convention.
Verified that all instances of `operation` were successfully renamed to `operations` in the specified TypeScript files and that no other code changes were introduced.
N/A

Rename operation to operations in code

---

package.json
yarn.lock

Updates the `@clearfeed-ai/quix-github-agent` to `1.2.14` and `@clearfeed-ai/quix-common-agent` to `1.2.0` in `package.json` and `yarn.lock`. This update was requested after the `github` package was published.
The changes were tested by running `yarn install` to ensure the `yarn.lock` file was correctly updated with the new dependency versions.
N/A

Update dependencies and merge
