clearfeed/quix

src/database/database.module.ts
src/database/migrations/06-create-github-configs.js
src/database/models/github-config.model.ts
src/database/models/index.ts
src/database/models/slack-workspace.model.ts
src/integrations/integrations-install.service.ts
src/integrations/integrations.controller.ts
src/integrations/types.ts
src/lib/constants.ts
src/slack/views/app_home.ts
src/slack/views/types.ts

This PR implements GitHub OAuth authentication for Quix, allowing users to authenticate via GitHub and store their credentials securely.
- Added a new table `github_configs` to store GitHub authentication details.
- Fields include `github_id`, `access_token` (encrypted), `username`, `full_name`, `avatar`, `scopes`, and `team_id`.
- Established a foreign key relationship with `slack_workspaces` via `team_id`.
- Introduced `GithubConfig` model with Sequelize decorators.
- Implemented encryption for storing `access_token` securely.
- Implemented `github()` method to handle GitHub OAuth flow.
- Added state validation and token exchange mechanism.
- Fetched user details from GitHub API and stored them in the database.
- Emitted `GITHUB_CONNECTED` event upon successful authentication.
1. Set …

[FEAT]: Implement GitHub OAuth authentication flow with secure token storage

---

src/lib/constants.ts

✅ What’s done:
- Updated github successful integration message.

fix(constants): Update GitHub connectedText for improved user guidance

---

agent-packages/yarn.lock
src/database/migrations/09-add-access-settings-to-slack-workspaces.js
src/database/models/slack-workspace.model.ts
src/lib/constants.ts
src/lib/types/slack-workspace.ts
src/lib/utils/slack-constants.ts
src/slack/app_home.service.ts
src/slack/interactions.service.ts
src/slack/slack-events-handler.service.ts
src/slack/views/app_home.ts
src/slack/views/modals.ts

- Introduced a new migration to add 'access_settings' column to the 'slack_workspaces' table.
- Updated SlackWorkspace model to include 'access_settings' with default value for allowed users.

feat(database): Add access settings to Slack workspaces

---

agent-packages/yarn.lock
src/lib/constants.ts
src/lib/utils/slack-home.ts
src/slack/views/app_home.ts

- Enhanced the App Home view to include a new `getToolData` function, providing detailed connection information, available functions, and capabilities for selected tools (GitHub, Jira, HubSpot, PostgreSQL).
- Improved user guidance by displaying relevant metadata and examples based on the selected integration.

[FEAT]: 39 show list of supported functions against an integration

---

src/integrations/integrations.service.ts
src/slack/app_home.service.ts

- Implemented removeGithubConfig method to handle the removal of GitHub configurations for a specified team.
- Updated AppHomeService to include GitHub integration handling in the disconnect flow.

feat(integrations): Add feature to disconnect GitHub

---

src/lib/utils/slack.ts

- Updated the logic for determining the message author to include bot messages.
- Reformatted the input block submission handling for better readability and maintainability, ensuring consistent processing of various input types.

fix(slack): Refactor message author determination

---

agent-packages/packages/github/package.json
agent-packages/packages/github/src/index.ts
agent-packages/packages/github/src/tools.ts
agent-packages/packages/github/src/types.ts
yarn.lock

- Added methods for creating/updating files, pushing multiple files, and searching repositories.
- Introduced new types for handling file operations and repository management.
- Updated tools to include new functionalities for file manipulation and repository interactions.
**1. Repository Management**
- Create a new repository called "my-project" and initialize it with a README
- Create a new file called "config.json" in the main branch with this content: {...}
- Push these 3 files to the repo: index.js, package.json, and README.md
- Fork the repository "org/cool-project" to my account
- Create a new branch called "feature/auth" from main
- Get the contents of the "src/config.ts" file
- Search for repositories with "machine learning" in Python
**2. Pull Request Operations**
- Create a …

feat(github): Enhance GitHub service with new functionalities

---

agent-packages/packages/common/src/tools.ts
agent-packages/packages/github/package.json
agent-packages/packages/salesforce/src/tools.ts
src/llm/llm.service.ts

- Updated the system prompt to include tool descriptions for better clarity in tool selection.
- Enhanced logging for generated plans to improve traceability.

Fix plan generation

---

.prettierrc
src/database/migrations/20250403_create_conversation_states.js
src/database/models/conversation-state.model.ts
src/database/models/index.ts
src/database/models/slack-workspace.model.ts
src/llm/callback-manager.ts
src/llm/llm.service.ts
src/llm/types.ts
src/slack/slack-events-handler.service.ts

- Added functionality to capture tool calls in QuixCallBackManager.
- Enhanced message processing to include previous tool calls in the context.
- Updated conversation state model to store last tool calls and plans.
- Adjusted LLM service methods to utilize the new conversation state features.

Added conversation memory

---

src/database/models/slack-workspace.model.ts
src/lib/utils/slack-constants.ts
src/slack/views/app_home.ts

Trial expiry 
< 1 day remaining
1 day remaining
> 1 day
closes #86

feat(slack): Implement trial mode for OpenAI key usage

---

src/llm/llm.service.ts
src/llm/mcp.service.ts

resolves #86 
Removed unused functions
Removed duplicate queries

refactor: remove unused convertMcpToLangchainTools and generateResponse functions and optimize queries

---

.vscode/settings.json
src/database/migrations/20240503213000-add-default-prompt-to-integrations.js
src/database/models/github-config.model.ts
src/database/models/hubspot-config.model.ts
src/database/models/jira-config.model.ts
src/database/models/linear-config.model.ts
src/database/models/mcp-connection.model.ts
src/database/models/notion-config.model.ts
src/database/models/postgres-config.model.ts
src/database/models/salesforce-config.model.ts
src/lib/constants.ts
src/lib/types/common.ts
src/lib/utils/slack-constants.ts
src/lib/utils/slack.ts
src/llm/callback-manager.ts
src/llm/llm.service.ts
src/llm/tool.service.ts
src/llm/types.ts
src/slack/app_home.service.ts
src/slack/interactions.service.ts
src/slack/slack-events-handler.service.ts
src/slack/views/app_home.ts
src/slack/views/modals.ts
src/slack/views/types.ts

- Updated `createLLMContext` to include `currentMessageTs` for message filtering.
- Modified `processMessage` to accept `authorName` for personalized prompts.
- Enhanced prompt generation in `LlmService` to utilize author-specific context.
- Refactored tool configuration to support structured tools with associated configurations.
- Improved integration handling in `ToolService` to return tools with their configurations.
- Updated Slack event handling to pass user names for better context in responses.

Support for default prompts, personalization & prompt tuning

---

agent-packages/.gitignore
agent-packages/packages/github/package.json
agent-packages/packages/github/src/index.ts
agent-packages/packages/github/src/tools.ts
agent-packages/packages/github/src/types.ts
agent-packages/packages/github/src/types/index.ts
agent-packages/packages/github/src/types/oktokit.d.ts
agent-packages/packages/github/tsconfig.json
agent-packages/yarn.lock
package.json
src/llm/tool.service.ts
src/slack/app_home.service.ts
src/slack/views/app_home.ts
yarn.lock

chore: update @okokit/rest in agent-packages/github to latest version to resolve security vulnerabilities related to @oktokit/rest

---

src/lib/constants.ts
src/llm/llm.service.ts
src/llm/tool.service.ts
src/llm/types.ts

Revert "chore: Remove Langchain tool selection and improve the prompt for planning phase"

---

src/database/migrations/20250407202247-add-message-count-to-conversation-states.js
src/database/models/conversation-state.model.ts
src/database/models/slack-workspace.model.ts
src/lib/utils/slack-constants.ts
src/llm/llm.provider.ts
src/llm/llm.service.ts
src/llm/types.ts
src/slack/slack-events-handler.service.ts
src/slack/slack.controller.ts

Tested by setting the limit to 2
Tested by setting the limit to 1
Resovles #116

feat: Restrict messages per conversation to 5 during trial

---

src/lib/constants.ts
src/lib/utils/slack.ts
src/slack/slack-events-handler.service.ts
src/slack/slack.service.ts

feat(slack): Show suggested prompts for a new conversation based on connected integrations

---

agent-packages/packages/okta/package.json
agent-packages/packages/okta/src/index.ts
agent-packages/packages/okta/src/tools.ts
agent-packages/packages/okta/src/types.ts
agent-packages/packages/okta/src/utils.ts
agent-packages/packages/okta/tsconfig.json
agent-packages/yarn.lock
package.json
src/database/migrations/20240605123000-create-okta-configs.js
src/database/models/index.ts
src/database/models/okta-config.model.ts
src/database/models/slack-workspace.model.ts
src/integrations/integrations-install.service.ts
src/integrations/integrations.service.ts
src/integrations/mcp.service.ts
src/lib/constants.ts
src/lib/types/common.ts
src/lib/utils/slack-constants.ts
src/llm/tool.service.ts
src/slack/app_home.service.ts
src/slack/constants.ts
src/slack/interactions.service.ts
src/slack/views/app_home.ts
src/slack/views/modals.ts
src/slack/views/types.ts
yarn.lock

v1 is pretty basic, need to add more tools to the okta package

Okta integration

---

src/slack/views/modals.ts

refactor(slack): Update modal titles for consistency and clarity

---

agent-packages/packages/hubspot/src/index.ts
agent-packages/packages/hubspot/src/types.ts

- Added functionality to batch fetch associated companies for deals.
- Introduced a new `HubspotOwner` interface to represent owner details.
- Refactored deal processing to include associated companies and optional owner information.
- Improved error handling in the owner retrieval process.
**If Trial Free account is activated:**
**If Trial Free account is deactivated:**

feat(hubspot): Enhance owner and companies retrieval in search deals tool.

---

agent-packages/packages/okta/package.json
agent-packages/packages/okta/src/index.ts
agent-packages/packages/okta/src/tools.ts
agent-packages/packages/okta/src/types.ts
package.json
yarn.lock

Added Okta Client Initialization for PrivateKey Route

Added Okta Client Initialization for PrivateKey

---

agent-packages/packages/okta/package.json
agent-packages/packages/okta/src/index.ts
agent-packages/packages/okta/src/tools.ts
package.json
yarn.lock

- Updated the `listUsers` method to accept search and filter parameters.
- Improved the tool description for listing Okta users to clarify usage of search and filter parameters.
- search parameter supports search by any profile attribute (including custom attribute)
- filter parameter is used to search with subset of properties and also, returned users include those with the DEPROVISIONED status.
[API Reference](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/User/#tag/User/operation/listUsers)
This change allows for more precise user retrieval from Okta, enhancing the integration's functionality.
- The tool `list_okta_users` is rigorously tested under following test cases manually:

feat(okta): enhance user listing with search and filter parameters
